module.exports = [
    "Tasarruf hesaplarına yatırım yaparak zengin olmuş kaç milyoner tanıyorsunuz? Söyleyeceklerim bu kadar.\n- Robert G. Allen",
    "Her gün bir şey öğren. Özellikle de diğerlerinin deneyimlerinden. Bu daha ucuz!\n- John Bogle",
    "Aptalların zaman kaybı dediği şey, çoğu zaman en iyi yatırımdır.\n- Nassim Nicholas Taleb",
    "Yatırım yapmayı asla bırakma. Gelişmeyi asla bırakma. Yeni bir şeyler yapmayı asla bırakma.\n- Bob Parsons",
    "En iyisini bekle, en kötüsüne hazır ol ve kazandığını sermayeleştir\n- Zig Zaglar",
    "Bilge bir kişi parayı kafasının içinde tutmalı, kalbinde değil.\n- Jonathan Swift",
    "Fiyat, ödediğiniz; değer ise elde ettiğinizdir.\n- Warren Buffett",
    "Yatırım yaparken rahat olan çok nadiren kazandırır.\n- Robert Arnott",
    "Zamanınız kısıtlı, başkasının hayatını yaşayarak onu boşa harcamayın.\n- Steve Jobs",
    "Ekonomi, somut maddelerin konusu değildir. Ekonominin konusu, insanlar ve insanların anlamları ile hareketleri üzerinedir.\n- Ludwig von Mises",
    "Dün öngördüklerinin, bugün neden gerçekleşmediğini yarın açıklayabilen insana ekonomist diyoruz.\n- Laurence J. Peter",
    "Keşif, yenilikleri sürükleyen bir motordur. Yenilik, ekonomik gelişim sağlar. Bu yüzden haydi keşfetmeye!\n- Edith Widder",
    "ÇALIŞMAK ÇALIŞMAK ÇALIŞMAK...\n- Sakıp Sabancı",
    "Ekonomisi zayıf bir ulus, yoksulluktan ve düşkünlükten kurtulamaz; güçlü bir uygarlığa, kalkınma ve mutluluğa kavuşamaz; toplumsal ve siyasal yıkımlardan kaçamaz.\n- Atatürk",
    "Eğer girişim ilerliyorsa, bolluk ekonomi ile birlikte artar; ama girişim yoksa bolluk ekonomi ile birlikte çürür.\n- John Maynard Keynes",
    "Ekonominin tabii kanunları vardır. Bu kanunların dışına çıkarak nehri tersine akıtmayalım.\n- Turgut Özal",
    "Bir milletin parasını kontrol eden, o milleti de kontrol eder.\n- E.Garfield",
    "Tasarruf, bir kimseye serbestiyet kazandırır, tevazu, bir kimseyi kabiliyetli yapabilir.\n- Lao Tzu",
    "Tam bağımsızlık ancak ekonomik bağımsızlıkla olur.\n- Atatürk",
    "Lüks, zengini yıkar ve fakirlerin sefaletini bir kat daha arttırır.\n- Denis Diderot",
    "Ekonomi, gelecekteki gelişmeleri karşılamak için bugünden yaptığımız hazırlıklardır.\n- Calvin Coolidge",
    "İktisada riayet eden kimse, fakir olmaz.\n- Hz. Muhammed (sav.)",
    "Enflasyon, taşınmanıza gerek kalmadan, daha pahalı bir muhitte oturmanızı sağlar.\n- Paul Getty",
    "Ekonomik kalkınma, Türkiye’nin hür, bağımsız, daima daha kuvvetli, daima daha refahlı Türkiye idealinin bel kemiğidir.\n- Atatürk",
    "İş hayatındaki sürprizlerin yüzde doksan dokuzu olumsuzdur.\n- Harold S. Geneen",
    "Tüm ekonomik çabalar, yıkımı önlemeye değil, tam tersi hızlandırmaya yönelik görünüyor.\n- Kenneth Watt",
    "Hükümetin ekonomi görüşü 1-2 kelimeyle özetlenebilir: hareketlenirse vergilendir, hareket devam ediyorsa düzenle, hareket durmuşsa destekle.\n- Ronald Reagan",
    "îktisat bilmenin yararı, ekonomik güçlüklere geçerli çözümler bulmak değil, iktisatçılar tarafından aldatılmayı önlemektir.\n- John Robinson",
    "Bir adam sadece para kazanmak fikriyle işe başladıysa, büyük ihtimalle, yapamayacaktır.\n- Joyce Claude Hall",
    "Yalnızca ekonomist olan bir ekonomist, şayet pozitif bir tehlike değilse, bilim için büyük bir problem olacaktır.\n- Von Hayek",
    "Nüfus miktarı da yalnız rakamla sayılmamalı; çünkü az kazanıp çok sarf eden az nüfus, azla geçinip çok biriktiren fazla nüfustan daha çabuk devleti yıpratır.\n- Francis Bacon",
    "Ekonomi hakkında konuşma yapmanın bacağından aşağı işemekle aynı olduğunu hiç düşündünüz mü? Size sımsıcak gelir ama başka kimsede aynı etkiyi bırakmaz.\n- Lyndon B. Johnson",
    "Masraflar, gelire uygun olarak artar.\n- John Murphy",
    "İktisat, yoksulların tozudur.\n- Tupper",
    "Eğer en iyi yüz ticari kuruluşu incelemeye kalkarsanız, eminim büyük bir çoğunluğunun başarısının özgün ve yenilikçi satış metotlarında gizli olduğunu fark edeceksiniz.\n- Alton Jones",
    "Bir ulus, ne kadar derin iktisadi bir bunalım içinde ise ziynet ve süs eşyası ile o kadar savurgandır.\n- Adolf Loon",
    "Hiçbir medeni devlet yoktur ki ordu ve donanmasından evvel, iktisadını düşünmüş olmasın.\n- Atatürk",
    "İktisat az malı çoğaltır, israf ise çok malı azaltır.\n- Hz. Ali (r.a.)",
    "Ekonomik lüzumu hasıl olunca, küçük paralar tedarik etmek için uğraşmaktansa, azar azar tasarruf etmek iyidir.\n- Francis Bacon",
    "Küçük harcamaları gözden kaçırmayın,bazen küçük bir delik koca bir gemiyi batırır.\n- Benjamin Franklin",
    "İktisat nedir ki?Üst sınıfın alt sınıfların emeğinin meyvalarına el koymak için icat ettiği bir bilim.\n - August Strindberg",
    "Eğer ahlak ideal bir dünyayı temsil ediyorsa,o zaman ekonomi de fiili dünyayı temsil eder.\n- Jach London",
    "Ekonomi bilimi,maskeler konusunda çok şey öğretmişti.Ekonomide hiç bir şey asla göründüğü gibidir.\n- Eduardo Galeano",
    "ABD,dünya ekonomisinin asalağıdır.\n- Putin",
    "Yaşamın tek anlamı ekonomi ise o yaşam,ölümcül bir hastalığın pençesinde demektir.Çünkü sınırsız gelişme,bu sınırlı dünyaya sığmaz.\n- Erich Fromm",
    "İçinde bulumduğumuz rekabetçilik üzerine kurulu ekonomi,başarsısızlığı bir hastalık olarak tarif eder.\n- Kemal Sayar",
    "Dinci ve ırkçi robot militanların önünü kesecek en doğru yöntem ise,eşitsizlikleri ortadan kaldıracak sağlam bir ekonomi,aklı özgürleştirip aydınlatacak sağlıklı bir eğitimdir.\n- Necla Arat",
    "İktisat,davranışları inceleyen bilim dalıydı.\n- H.Pink",
    "Ekonomi kötüleştikçe,ekonomistler iyileşir.\n- Alfred Zaubermen",
    "Esasen,her şey tam da ekonomi kitaplarının yazdığı gibi oluyordu.Savaşı izleyen yıllarda önce enflasyon,ardından işsizlik gelmişti.\n- Osman Balcıoğlu",
    "Zihinsel ekonomi kuramayan kaybolur.\n- Tahir Musa Ceylan",
    "Onun için kıyamet alametleri açıktı:Sadece siyaset,ekonomi ve futbol konuşulan bir dünya.\n- İbrahim Paşalı",
    "Bir gezegen dolusu insan,ekonomik zorunluğun dikte ettiğinin karşısında bir hiçtir.\n- İsaac Asimov",
    "Kapitalist ekonomi sistemi durmazsa dünya duracak.\n- Sebuhi Quluzade",
    "Ülkenin en büyük problemi ahlak!Ne terör,ne ekonomi ne başka bir şey.Gün be gün ahlaksız insanlar tarafından kuşatılıyoruz.\n- Kolektif",
    "21. yüzyılın kölelik sistemi kapitalizmin hakim olduğu modern ekonomidir.Bu sistemde en çok çalışan işçi sınıfdır;en az kazanan da odur.En az çalışan patronlardır;en çok kazanan da onlardır.\n- Sebuhi Quluzade",
    "Ekonominin ilk kurali: Yeryüzündeki her bir ekonomist için onun söylediginin tam tersini savunan bir diger ekonomist bulunur.\nEkonominin ikinci kurali: Her ikisi de hatalıdır.",
    "Ekonomik raporlarin temelinde, satın almak istediginizi almak için en iyi zamanın aslında geçen yıl oldugu gerçeği yatar.\n - Marty Allen",
    "Bir odaya iki ekonomist girerse iki farkli fikir duyarsiniz. Gerçi bu ekonomistlerden biri Lord Keynes ise üç farkli fikir duyarsiniz.\n- Winston Churchill",
    'Birisinin ekonomi uzmani olmasindan süphe ediyorsunuz… Gerçekten ekonomist olup olmadıgını nasıl anlarsiniz? Su soruyu soracaksınız…\n“Bilgisizlikle umursamazlık arasinda ne fark vardir?”\nEger cevap…\n“Bilmiyorum ve umrumda da degil” şeklinde gelirse…O bir ekonomistdir.',
]