module.exports = [
    "Tasarruf hesaplarına yatırım yaparak zengin olmuş kaç milyoner tanıyorsunuz? Söyleyeceklerim bu kadar.\n- Robert G. Allen",
    "Her gün bir şey öğren. Özellikle de diğerlerinin deneyimlerinden. Bu daha ucuz!\n- John Bogle",
    "Aptalların zaman kaybı dediği şey, çoğu zaman en iyi yatırımdır.\n- Nassim Nicholas Taleb",
    "Yatırım yapmayı asla bırakma. Gelişmeyi asla bırakma. Yeni bir şeyler yapmayı asla bırakma.\n- Bob Parsons",
    "En iyisini bekle, en kötüsüne hazır ol ve kazandığını sermayeleştir\n- Zig Zaglar",
    "Bilge bir kişi parayı kafasının içinde tutmalı, kalbinde değil.\n- Jonathan Swift",
    "Fiyat, ödediğiniz; değer ise elde ettiğinizdir.\n- Warren Buffett",
    "Yatırım yaparken rahat olan çok nadiren kazandırır.\n- Robert Arnott",
    "Zamanınız kısıtlı, başkasının hayatını yaşayarak onu boşa harcamayın.\n- Steve Jobs",
    "Ekonomi, somut maddelerin konusu değildir. Ekonominin konusu, insanlar ve insanların anlamları ile hareketleri üzerinedir.\n- Ludwig von Mises",
    "Dün öngördüklerinin, bugün neden gerçekleşmediğini yarın açıklayabilen insana ekonomist diyoruz.\n- Laurence J. Peter",
    "Keşif, yenilikleri sürükleyen bir motordur. Yenilik, ekonomik gelişim sağlar. Bu yüzden haydi keşfetmeye!\n- Edith Widder",
    "ÇALIŞMAK ÇALIŞMAK ÇALIŞMAK...\n- Sakıp Sabancı",
    "Ekonomisi zayıf bir ulus, yoksulluktan ve düşkünlükten kurtulamaz; güçlü bir uygarlığa, kalkınma ve mutluluğa kavuşamaz; toplumsal ve siyasal yıkımlardan kaçamaz.\n- Atatürk",
    "Eğer girişim ilerliyorsa, bolluk ekonomi ile birlikte artar; ama girişim yoksa bolluk ekonomi ile birlikte çürür.\n- John Maynard Keynes",
    "Ekonominin tabii kanunları vardır. Bu kanunların dışına çıkarak nehri tersine akıtmayalım.\n- Turgut Özal",
    "Bir milletin parasını kontrol eden, o milleti de kontrol eder.\n- E.Garfield",
    "Tasarruf, bir kimseye serbestiyet kazandırır, tevazu, bir kimseyi kabiliyetli yapabilir.\n- Lao Tzu",
    "Tam bağımsızlık ancak ekonomik bağımsızlıkla olur.\n- Atatürk",
    "Lüks, zengini yıkar ve fakirlerin sefaletini bir kat daha arttırır.\n- Denis Diderot",
    "Ekonomi, gelecekteki gelişmeleri karşılamak için bugünden yaptığımız hazırlıklardır.\n- Calvin Coolidge",
    "İktisada riayet eden kimse, fakir olmaz.\n- Hz. Muhammed (sav.)",
    "Enflasyon, taşınmanıza gerek kalmadan, daha pahalı bir muhitte oturmanızı sağlar.\n- Paul Getty",
    "Ekonomik kalkınma, Türkiye’nin hür, bağımsız, daima daha kuvvetli, daima daha refahlı Türkiye idealinin bel kemiğidir.\n- Atatürk",
    "İş hayatındaki sürprizlerin yüzde doksan dokuzu olumsuzdur.\n- Harold S. Geneen",
    "Tüm ekonomik çabalar, yıkımı önlemeye değil, tam tersi hızlandırmaya yönelik görünüyor.\n- Kenneth Watt",
    "Hükümetin ekonomi görüşü 1-2 kelimeyle özetlenebilir: hareketlenirse vergilendir, hareket devam ediyorsa düzenle, hareket durmuşsa destekle.\n- Ronald Reagan",
    "îktisat bilmenin yararı, ekonomik güçlüklere geçerli çözümler bulmak değil, iktisatçılar tarafından aldatılmayı önlemektir.\n- John Robinson",
    "Bir adam sadece para kazanmak fikriyle işe başladıysa, büyük ihtimalle, yapamayacaktır.\n- Joyce Claude Hall",
    "Yalnızca ekonomist olan bir ekonomist, şayet pozitif bir tehlike değilse, bilim için büyük bir problem olacaktır.\n- Von Hayek",
    "Nüfus miktarı da yalnız rakamla sayılmamalı; çünkü az kazanıp çok sarf eden az nüfus, azla geçinip çok biriktiren fazla nüfustan daha çabuk devleti yıpratır.\n- Francis Bacon",
    "Ekonomi hakkında konuşma yapmanın bacağından aşağı işemekle aynı olduğunu hiç düşündünüz mü? Size sımsıcak gelir ama başka kimsede aynı etkiyi bırakmaz.\n- Lyndon B. Johnson",
    "Masraflar, gelire uygun olarak artar.\n- John Murphy",
    "İktisat, yoksulların tozudur.\n- Tupper",
    "Eğer en iyi yüz ticari kuruluşu incelemeye kalkarsanız, eminim büyük bir çoğunluğunun başarısının özgün ve yenilikçi satış metotlarında gizli olduğunu fark edeceksiniz.\n- Alton Jones",
    "Bir ulus, ne kadar derin iktisadi bir bunalım içinde ise ziynet ve süs eşyası ile o kadar savurgandır.\n- Adolf Loon",
    "Hiçbir medeni devlet yoktur ki ordu ve donanmasından evvel, iktisadını düşünmüş olmasın.\n- Atatürk",
    "İktisat az malı çoğaltır, israf ise çok malı azaltır.\n- Hz. Ali (r.a.)",
    "Ekonomik lüzumu hasıl olunca, küçük paralar tedarik etmek için uğraşmaktansa, azar azar tasarruf etmek iyidir.\n- Francis Bacon",
    "Küçük harcamaları gözden kaçırmayın,bazen küçük bir delik koca bir gemiyi batırır.\n- Benjamin Franklin",
    "İktisat nedir ki?Üst sınıfın alt sınıfların emeğinin meyvalarına el koymak için icat ettiği bir bilim.\n - August Strindberg",
    "Eğer ahlak ideal bir dünyayı temsil ediyorsa,o zaman ekonomi de fiili dünyayı temsil eder.\n- Jach London",
    "Ekonomi bilimi,maskeler konusunda çok şey öğretmişti.Ekonomide hiç bir şey asla göründüğü gibidir.\n- Eduardo Galeano",
    "ABD,dünya ekonomisinin asalağıdır.\n- Putin",
    "Yaşamın tek anlamı ekonomi ise o yaşam,ölümcül bir hastalığın pençesinde demektir.Çünkü sınırsız gelişme,bu sınırlı dünyaya sığmaz.\n- Erich Fromm",
    "İçinde bulumduğumuz rekabetçilik üzerine kurulu ekonomi,başarsısızlığı bir hastalık olarak tarif eder.\n- Kemal Sayar",
    "Dinci ve ırkçi robot militanların önünü kesecek en doğru yöntem ise,eşitsizlikleri ortadan kaldıracak sağlam bir ekonomi,aklı özgürleştirip aydınlatacak sağlıklı bir eğitimdir.\n- Necla Arat",
    "İktisat,davranışları inceleyen bilim dalıydı.\n- H.Pink",
    "Ekonomi kötüleştikçe,ekonomistler iyileşir.\n- Alfred Zaubermen",
    "Esasen,her şey tam da ekonomi kitaplarının yazdığı gibi oluyordu.Savaşı izleyen yıllarda önce enflasyon,ardından işsizlik gelmişti.\n- Osman Balcıoğlu",
    "Zihinsel ekonomi kuramayan kaybolur.\n- Tahir Musa Ceylan",
    "Onun için kıyamet alametleri açıktı:Sadece siyaset,ekonomi ve futbol konuşulan bir dünya.\n- İbrahim Paşalı",
    "Bir gezegen dolusu insan,ekonomik zorunluğun dikte ettiğinin karşısında bir hiçtir.\n- İsaac Asimov",
    "Kapitalist ekonomi sistemi durmazsa dünya duracak.\n- Sebuhi Quluzade",
    "Ülkenin en büyük problemi ahlak!Ne terör,ne ekonomi ne başka bir şey.Gün be gün ahlaksız insanlar tarafından kuşatılıyoruz.\n- Kolektif",
    "21. yüzyılın kölelik sistemi kapitalizmin hakim olduğu modern ekonomidir.Bu sistemde en çok çalışan işçi sınıfdır;en az kazanan da odur.En az çalışan patronlardır;en çok kazanan da onlardır.\n- Sebuhi Quluzade",
    "Ekonominin ilk kurali: Yeryüzündeki her bir ekonomist için onun söylediginin tam tersini savunan bir diger ekonomist bulunur.\nEkonominin ikinci kurali: Her ikisi de hatalıdır.",
    "Ekonomik raporlarin temelinde, satın almak istediginizi almak için en iyi zamanın aslında geçen yıl oldugu gerçeği yatar.\n - Marty Allen",
    "Bir odaya iki ekonomist girerse iki farkli fikir duyarsiniz. Gerçi bu ekonomistlerden biri Lord Keynes ise üç farkli fikir duyarsiniz.\n- Winston Churchill",
    'Birisinin ekonomi uzmani olmasindan süphe ediyorsunuz… Gerçekten ekonomist olup olmadıgını nasıl anlarsiniz? Su soruyu soracaksınız…\n“Bilgisizlikle umursamazlık arasinda ne fark vardir?”\nEger cevap…\n“Bilmiyorum ve umrumda da degil” şeklinde gelirse…O bir ekonomistdir.',
    "Para size arkadaş satın alınamaz ama daha kaliteli düşmanlar getirebilir.\n- Spike Milligan",
    "Para hiç bir zaman insanı mutlu etmemiştir ve etmeyecektir, doğasında mutluluk yaratan hiç bir şey yoktur. Bir insan ne kadar çok para kazanırsa, o kadar fazlasını isteyecektir.\n- Benjamin Franklin",
    "Bilge bir kişi parayı kafasının içinde tutmalı, kalbinde değil.\n- Jonathan Swift",
    "Para benim için hiç bir zaman motivasyon kaynağı olmamıştır, sadece kendimi takip etmem için bir yoldur. Asıl heyecan oyunu oynamaktadır.\n- Donald Trump",
    "Para çoğu zaman çok fazlaya mal olur.\n- Ralph Waldo Emerson",
    "Bir insan satın alamadığı şeyler kadar zengindir.\n- Henry David Thoreau",
    "Yalnızca yapmayı sevdiğiniz şeylerde gerçekten başarılı olabilirsiniz. Parayı hedefiniz yapmayın. Onun yerine yapmayı çok sevdiğiniz şeylerin arkasından gidin ve onları o kadar iyi yapın ki, insanlar gözlerini üstünüzden alamasın.\n- Maya Angelou",
    "Parayı genellikle kendinize çekersiniz, peşinden koşmazsınız.\n- Jim Rohn",
    "Sahip olan değil, bağışlayan zengindir.\n- Erich Fromm",
    "Hiç bir zaman kendi gücünüzle edinebileceğiniz bir şey için dilenmeyin.\n- Miguel de Cervantes",
    "Şiir sanatında hiç para yoktur, fakat parada da şiirsel hiç bir şey yoktur.\n Robert Graves",
    "Çok parası olan fakir bir insan gibi yaşamak isterim.\n- Pablo Picasso",
    "Para konusuna gelindiğinde herkes aynı dindendir.\n- Voltaire",
    "Para güçtür, özgürlüktür, bir tampondur, bütün kötülüklerin kaynağı ve bütün nimetlerin toplamıdır.\n- Carl Sandburg",
    "Büyüleyici olmaktansa, daimi bir gelirinin olması daha iyidir.\n- Oscar Wilde",
    "Bir insanın para sahibi olup olmaması ya da giysilerinin olup olmaması önemli değildir. Herşeyin sonunda insan kendiyle başbaşa kalacaktır.\n- Billy Idol",
    "Ne kadara sahip olduğunuzun ne önemi var. Asıl önemli olan sahip olmadıklarınızın ne kadar olduğudur.\n- Seneca",
    "Paranızı mahremiyet satın almak için kullanırsınız, çünkü hayatınızın büyük bir çoğunluğunu normal olmanıza izin verilmeden geçirmişsinizdir.\n- Johnny Depp",
    "Parayı kazanmak değil, onu muhafaza edebilmek sanattır.\n- Anonim",
    "Sevgi dolu bir düşüncenin ışığı benim için paradan daha değerlidir.\n- Thomas Jefferson",
    "Para bilge adamın dinidir.\n- Euripides",
    "Piyasa 10 yıl boyunca kapansa bile gurur duyacağınız birşey alın.\n- Warren Buffett",
    "Bütün iyi yumurtalarınızı bir sepete koyun ve o sepeti izleyin.\n- Andrew Carnegie",
    "Ne borç verin ne de borç alın, çünkü borç veren çoğu zaman parasını ve arkadaşını kaybeder, borç almak da ekonominin köşelerini köreltir.\n- William Shakespeare",
    "Para gübre gibidir, dağıtılmadıkça bir işe yaramaz.\n- Francis Bacon",
    "Para mutluluk satın alamaz, ama kesinlikle size daha kaliteli anılar verecektir.\n- Ronald Reagan",
    "Paranın nereye harcandığını parayı harcayana asla sormayın. Hiç kimse her bir kuruşunun nereye gittiğini düşünmek için doğmamıştır.\n- Robert Frost",
    "Param olduğunda herkes bana kardeşim derdi.\n- Polonya atasözü",
    "Parayla çok ilgilenmiyorum çünkü para bana aşkı satın alamaz.\n The Beatles",
    "Eğer hiç kimsenin size değer vermediğini düşünüyorsanız bir kaç araba taksitinizi ödemeyi unutun.\n Earl Wilson",
    "Para ileride isteyebileceğimiz bir şeyi alabileceğimizin garantisidir. Şu anda bir şey ihtiyacımız olmamasa bile, ileride isteyebileceğimiz bir şeyin alınması için bir garantidir.\n- Aristotle",
    "Para ve kadınlar arkasından en çok koşulan ve ne oldukları konusunda en az bilgiye sahip olduğumuz iki konudur.\n- Will Rogers",
    "Başarı için benim formülüm: Erken kalk, geç saatlere kadar çalış ve petrol bul.\n- JP Getty",
    "Ben parayı geleneksel yoldan kazandım. Çok zengin bir akrabama ölmeden önce çok iyi davrandım.\n Malcolm Forbes",
    "Tutumluluk bütün erdemleri içinde barındırır.\n Cicero",
    "Sermaye kötü bir şey değildir, kötü olan sermayenin kötüye kullanımıdır. Sermaye o ya da bu şekilde kullanılacaktır.\n- Gandhi",
    "Parayı kaybeden çok kaybeder, arkadaş kaybeden daha da çok kaybeder, inanç kaybeden herşeyini kaybeder.\n- Eleanor Roosevelt",
    "Neye sahip olduğunu ve o şeye niye sahip olduğunu bil.\n- Peter Lynch",
    "Resmi eğitim sizin geçinmenizi sağlar, insanın kendini yetiştirmesi ona bir servet sağlar.\n- Jim Rohn",
    "Bir hazine, hazine olduğunu için değerli olmalı; alabileceği şeyler için değil.\n- Graham Greene",
    "Parayı zevk için tehlikeli şekilde kullanmak, çalıntı bir arabayla hız yapmak gibidir. Onu durdurmak için arabayı değil, şöförü tutuklamalısınız.\n- Woodrow Wilson",
    "Alacağı ceketin, o ceketi yapanları aç bırakacak kadar ucuz olmasını isteyen adama acırım.\n- Benjamin Harrison",
    "Fırsat çoğu insan tarafından kaçırılır, çünkü fırsat iş tulumu giymiştir ve çalışmaya benzer.\n- Thomas Edison",
    "Bilgiye yapılan yatırım en yüksek getiri sağlar.\n- Benjamin Franklin",
    "En iyisini bekle, en kötüsüne hazır ol ve kazandığını sermayeleştir.\n- Zig Ziglar",
    "Yatırım yaparken rahat olan çok nadiren kazandırır.\n- Robert Arnott",
    "Bana önceliklerinden bahsetme, paranı nereye harcadığını göster, ben de sana ne olduklarını söyleyeyim.\n- James W. Frick",
    "Zaman hayatınızdaki tek paradır ve sadece siz onun nasıl harcananacağına karar verebilirsiniz. Başka insanların paranızıharcamasına izin vermeyin.\n- Carl Sandburg",
    "Parayı tanrınız yaparsanız, şeytan gibi başınıza bela olur.\n- Henry Fielding",
    "Eğer zengin olmak istiyorsanız, kazanmak kadar biriktirmeyi de düşünün.\n- Ben Franklin",
    "Derdiniz piyasanın ne yapacağı değil piyasanın yapacaklarına karşı sizin ne yapacağınız olsun.\n(Michael Carr)",
    "Basitçe yatırım yapın\n(Warren Buffett)",
    "İnsan 10 yanlış girişiminden dört tanesinde bile zararını kabul edip geri çekilse servet kazanır.\n(Bernard Baruch)",
    "Bir yatırımcı için en önemli nitelik zeka değil, mizaçtır. Kalabalığın içinde olmaktan da karşı durmaktan da zevk almamanız gerekir.\n(Warren Buffet)",
    "Bir pozisyon aldığınızda işler beklediğiniz gibi gitmiyorsa o pozisyonu hemen terk edip zararı olabildiğince küçük tutun.\n(Gary Bielfeldt)",
    "Yatırım felsefesi gerçekten salt zekayla değil mizaçla ilgili bir şeydir. Aslında uygun bir mizaç yüksek IQ’ya her zaman üstün gelir.\n(Michael Mauboussın)",
    "Zarar etmekten korkamazsınız. Bu işte başarılı olanlar, para kaybetmeyi göze alan kişilerdir.\n(Jack Schwager)",
    "Öz disiplin başarının en önemli unsurudur. Öz disiplin yoksa, diğer her şey önemsizdir.\n(Howard Fleischman)",
    "Yanımdaki herhangi bir trader’dan daha iyi değilim, sadece hatalarımı kabul etmekte ve bir sonraki fırsata yönelmekte daha hızlıyım.\n(George Saros)",
    "Gelecek hiçbir zaman belirgin değildir ve piyasalarda keyif veren bir ortak görüş için çok yüksek bedel ödersiniz. Belirsizlik, uzun vadeli değerleri satın alan yatırımcının dostudur.\n(Warren Buffett)",
    "Borsada başarılı spekülasyonun temeli, insanların geçmişte yaptıkları hataları gelecekte de sürdürecekleri varsayımı üzerine kuruludur.\n(Thomas F.Woodlock)",
    "“Hiç zengin olan bir teknik analist görmedim” diyenlere hep gülmüşümdür. Bu kadar saçma ve küstahça bir şey daha duymadım. Dokuz yıl boyunca temel analiz kullandıktan sonra, teknik analizci olarak zengin oldum.“\n(Marty Schwartz)"
]